source = ~/.config/hypr/apps/bg3.conf
source = ~/.config/hypr/apps/indiana-jones.conf
source = ~/.config/hypr/apps/steam.conf
source = ~/.config/hypr/apps/zen.conf
source = ~/.config/hypr/apps/wow.conf
