# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# HDMI port: mirror display. To see device name, use `hyprctl monitors`

$mainMonitor = DP-2
$leftMonitor = DP-3
$rightMonitor = DP-1

# main monitor
monitorv2 {
    output = $mainMonitor
    mode = 3840x2160@120
    position = 0x0
    scale = 1.2
    bitdepth = 10
    cm = hdr
    sdrbrightness = 1.5
    sdrsaturation = 1.2
    vrr = 1
}

# left monitor
monitorv2 {
  output = $leftMonitor
  mode = 2560x1440@120
  position = -2560x360
  scale = 1
}

# right monitor
monitorv2 {
  output = $rightMonitor
  mode = 2560x1440@120
  position = 3200x360
  scale = 1
}

workspace=1,monitor:$mainMonitor
workspace=2,monitor:$mainMonitor
workspace=3,monitor:$mainMonitor
workspace=4,monitor:$mainMonitor
workspace=5,monitor:$mainMonitor
workspace=6,monitor:$mainMonitor
workspace=7,monitor:$mainMonitor
workspace=8,monitor:$mainMonitor
workspace=9,monitor:$mainMonitor
workspace=10,monitor:$mainMonitor

workspace=11,monitor:$leftMonitor
workspace=12,monitor:$leftMonitor
workspace=13,monitor:$leftMonitor
workspace=14,monitor:$leftMonitor
workspace=15,monitor:$leftMonitor
workspace=16,monitor:$leftMonitor
workspace=17,monitor:$leftMonitor
workspace=18,monitor:$leftMonitor
workspace=19,monitor:$leftMonitor
workspace=20,monitor:$leftMonitor

workspace=21,monitor:$rightMonitor
workspace=22,monitor:$rightMonitor
workspace=23,monitor:$rightMonitor
workspace=24,monitor:$rightMonitor
workspace=25,monitor:$rightMonitor
workspace=26,monitor:$rightMonitor
workspace=27,monitor:$rightMonitor
workspace=28,monitor:$rightMonitor
workspace=29,monitor:$rightMonitor
workspace=30,monitor:$rightMonitor

# disable scaling for apps outside of desktop
 xwayland {
    force_zero_scaling = true
}

# mouse sensitivity
input {
    sensitivity = -0.4
}
