# General opacity rule
windowrulev2 = opacity 1.0 1.0, class:.*

# Scroll faster in the terminal
windowrulev2 = scrolltouchpad 1.5, class:(Alacritty)

# About
windowrule = unset, class:About
windowrule = size 800 700, class:About
