windowrule = float, class:steam
windowrule = center, class:steam, title:Sign in to Steam
windowrule = center, class:steam, title:Steam
windowrule = monitor 1, class:steam, title:Sign in to Steam
windowrule = monitor 1, class:steam, title:Steam
windowrule = size 2400 1400, class:steam, title:Steam
windowrule = size 460 800, class:steam, title:Friends List
# calculation based on 4k resolution 1.2 scale
# X = (3840 / 1.20) - 460 - 8 = 2726, Y = (2160 / 1.20) - 800 - 8 = 992
windowrule = move 2734 994, class:steam, title:Friends List
